name: holoseq-dev
channels:
  - conda-forge
  - pyviz/label/dev
dependencies:
  - python >3.10,<3.13
  - bokeh
  - dask[dataframe]
  - datashader
  - holoviews
  - pre-commit
  - ruff
  - jupyterlab
  - pytest
  - pytest-cov
  - nbsite>=0.8.4,<0.9.0
  - setuptools
  - setuptools-scm