name: Run tests
on:
  pull_request:
  push:
    branches: [main]
    paths-ignore:
      - "docs/"
      - "notebooks/"
      - "scripts/"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: ["3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,test]

      - name: Run ruff
        uses: astral-sh/ruff-action@v2

      - name: Run tests
        run: |
          pytest -v tests --cov=src/holoseq --cov-append
